// Named TypeScript equivalents of warden.compact's `Policy` and
// `MandateContext` structs — a copy of
// `infra/devnet/deploy-script-legacy/contract/src/types.ts`, itself
// documented there as structurally (not nominally) checked against the
// compiler's generated types. Duplicated here, not imported across
// directories, so this module stays entirely inside `apps/web` for Next.js's
// bundler — see `managed/` in this directory for why (generated by this
// app's own `compact:legacy` build step, from the same canonical source at
// `packages/contracts/src/warden.compact`).

export type Policy = {
  maxAmount: bigint;
  asset: Uint8Array;
  actionType: Uint8Array;
  destinationCategory: Uint8Array;
  expiry: bigint;
  actionCountLimit: bigint;
  salt: Uint8Array;
};

export type MandateContext = {
  principalPk: Uint8Array;
  agentPk: Uint8Array;
  policy: Policy;
};
